site_name: SciREX Documentation
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline 
        name: Switch to dark mode
      primary: teal
      accent: purple 
    - scheme: slate 
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode    
      primary: teal
      accent: lime

    
  logo: assets/logo.png

  # Add a custom vibrant logo here

nav:
  - Home: index.md
  - Core:
      - Machine Learning:
          - Supervised:
              - Classification: 
                  - base: api/core/ml/supervised/classification/base.md
                  - naive bayes: api/core/ml/supervised/classification/naive_bayes.md
                  - Logistic regression: api/core/ml/supervised/classification/logistic_regression.md
                  - Decision tree: api/core/ml/supervised/classification/decision_tree.md
                  - SVM: api/core/ml/supervised/classification/svm.md
          - Unsupervised:
              - Clustering: 
                  - Base: api/core/ml/unsupervised/clustering/base.md
                  - Kmeans: api/core/ml/unsupervised/clustering/kmeans.md
                  - Agglomerative: api/core/ml/unsupervised/clustering/agglomerative.md
                  - GMM: api/core/ml/unsupervised/clustering/gmm.md
                  - Hdbscan: api/core/ml/unsupervised/clustering/hdbscan.md
                  - Dbscan: api/core/ml/unsupervised/clustering/dbscan.md
                  - Optics: api/core/ml/unsupervised/clustering/optics.md
      - Deep Learning: 
          - tensorflow_wrapper: api/core/dl/tensorflow_wrapper.md
          - fcnn: api/core/dl/fcnn.md
      - SciML:
          - Geometry:
              - geometry_2d: api/core/sciml/geometry/geometry_2d.md
              - geometry: api/core/sciml/geometry/geometry.md
          - fe:
              - Chebyshev: api/core/sciml/fe/basis_2d_QN_Chebyshev_2.md
              - jacobi: api/core/sciml/fe/basis_2d_QN_Jacobi.md 
              - Legendre_Special: api/core/sciml/fe/basis_2d_QN_Legendre_Special.md
              - Legendre: api/core/sciml/fe/basis_2d_QN_Legendre.md
              - Function 2D: api/core/sciml/fe/basis_function_2d.md
              - Function 3D: api/core/sciml/fe/basis_function_3d.md
              - FE_transformation_2d: api/core/sciml/fe/fe_transformation_2d.md
              - FE_transformation_3d: api/core/sciml/fe/fe_transformation_3d.md
              - FE2D_Cell: api/core/sciml/fe/FE2D_Cell.md
              - fe2d_setup_main: api/core/sciml/fe/fe2d_setup_main.md
              - fespace: api/core/sciml/fe/fespace.md
              - fespace2d: api/core/sciml/fe/fespace2d.md
              - quad_affine: api/core/sciml/fe/quad_affine.md
              - quad_bilinear: api/core/sciml/fe/quad_bilinear.md
              - quadratureformulas_quad2d: api/core/sciml/fe/quadratureformulas_quad2d.md
              - quadratureformulas: api/core/sciml/fe/quadratureformulas.md    
          - fastvpinns:
            - data:
              - datahandler: api/core/sciml/fastvpinns/data/datahandler.md
              - datahandler2: api/core/sciml/fastvpinns/data/datahandler2d.md
            - Model:
              - Model hard : api/core/sciml/fastvpinns/model/model_hard.md
              - Model inverse domain: api/core/sciml/fastvpinns/model/model_inverse_domain.md
              - Model inverse : api/core/sciml/fastvpinns/model/model_inverse.md
              - Model  : api/core/sciml/fastvpinns/model/model.md
            - Physics:
              - cd2d_inverse_domain : api/core/sciml/fastvpinns/physics/cd2d_inverse_domain.md
              - cd2d_inverse: api/core/sciml/fastvpinns/physics/cd2d_inverse.md
              - cd2d: api/core/sciml/fastvpinns/physics/cd2d.md
              - helmholtz2d: api/core/sciml/fastvpinns/physics/helmholtz2d.md
              - poisson2d:  api/core/sciml/fastvpinns/physics/poisson2d.md
              - poissson2d Inverse :   api/core/sciml/fastvpinns/physics/poisson_2d_inverse.md          
          - Super Resolution:
              - Super Resolution: api/core/sciml/superresolution.md 
  - Tutorial:
          - Classification Tutorial: api/core/tutorial/classification_tutorial.md
  - Contribution:
          - contribution: api/core/Contribution/contribution.md         
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg


plugins:
  - mkdocstrings:
      handlers:
        python:
          options:
            rendering:
              show_source: true
            

              
  - search:
      lang: en
      #separator: "[\s\-]+"

extra_css:
  - assets/custom.css  # Custom vibrant colors

extra_javascript:
  - assets/custom.js  # Advanced interactivity like smooth scrolling or dynamic effects
